#!/usr/bin/env bash

BASE_URL=https://www.pagalworld.pw
ICON=~/.config/dunst/icons

query=$(printf '%s' "$*" | dmenu -c -p "search song :")
if [[ -n $query ]]; then
	song_selection=$(curl -s ${BASE_URL}/search?\cats=\5570\&\q=${query} | grep "download.html" | cut -d'"' -f2 | dmenu -l 10 -c)
else
	exit -1
fi

if [[ -n $song_selection ]]; then
	url_padding=$(echo https://www.pagalworld.pw${song_selection})
	dnld1=$(curl -s ${url_padding} | grep "audio/mpeg" | cut -d'"' -f2 | sed 's/ /%20/g')

	name=$(echo $dnld1 | sed 's/%20/_/g' | cut -d'/' -f5)
	dunstify -u normal -t 3000 -r "9993" -i ${ICON}/screenshot3.png "Downloading ${name}"
	curl -o ~/song/${name} $dnld1
	dunstify -u normal -t 3000 -r "9993" -i ${ICON}/screenshot3.png "${name} Downloaded"
else
	exit -1
fi
