#!/usr/bin/env bash

ICON=~/.config/dunst/icons
NOTIFY="dunstify -a "changevolume" -t 2000 -r 9993 -u normal"

function getVolume(){
	VOLUME=$(pulsemixer --get-volume | cut -d' ' -f1)
	$NOTIFY -i ${ICON}/volume.png "${VOLUME} %"
}

function getMute(){
	MUTE=$(pulsemixer --get-mute)
	if [[ $MUTE == "1" ]]; then
		$NOTIFY -i ${ICON}/volume_mute.png "0 %"
	else
		getVolume
	fi
}

function getMic(){
	MIC=$(pulsemixer --id source-1 --get-mute)
	if [[ $MIC == "1" ]]; then
		$NOTIFY -i ${ICON}/mic_off.png "OFF "
	else
		$NOTIFY -i ${ICON}/mic_on.png "ON "
	fi
}

case $1 in
   up)
	  pulsemixer --change-volume +2
	  getVolume
	  ;;
   down)
	  pulsemixer --change-volume -2
	  getVolume
	  ;;
   mute)
	  pulsemixer --toggle-mute
	  getMute
	  ;;
   mic)
	  pulsemixer --id source-1 --toggle-mute
	  getMic
	  ;;
   *) echo "Invalid Option"
esac
